add batch execute
UST-QuAntiL/qiskit-service pull request #33
Opened 2022-08-08 14:18 UTC by aaronschi

2022-08-09 12:20 UTC, mbeisel commented
Looks generally good.

However,
1. Extend execute tests to contain batch executions.
2. IBMQ QPUs have a maximum number of circuits that can be executed in one job. For example, the aer_qasm_simulator has a maximum of 300 circuits. To bypass this issue, the IBMQ JobManager has been introduced (https://qiskit.org/documentation/stubs/qiskit.providers.ibmq.managed.IBMQJobManager.html#qiskit.providers.ibmq.managed.IBMQJobManager).
--> It would be great if the qiskit-service can receive, e.g., 10,000 circuits and internally does the splitting etc., without the user needing to care about the maximum circuit limit (also add a test for a similar use-case).

2022-08-15 12:35 UTC, salmma commented
should also solve #36

2022-08-15 13:35 UTC, mbeisel commented on app/routes.py
> +    optimization_level = request.json.get('circuit transpile optimization level', 3)
Similar to other attributes use dashes "-" in between words.
Also, maybe slightly shorten the attribute name? For example: transpilation-optimization-level

2022-08-15 15:59 UTC, salmma requested changes
see comments

2022-08-16 06:37 UTC, salmma commented on app/tasks.py
> +        result.result = json.dumps(result_counts)
if only a single circuit was executed then return the first element in the array and not the array itself like it was before this PR.

2022-08-16 10:29 UTC, salmma requested changes
Please extend the README.md with one example to execute multiple circuits

2022-08-17 06:33 UTC, salmma approved these changes
LGTM

2022-08-17 06:34 UTC, merged